spring:
  datasource:
    url: jdbc:h2:mem:demo25db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE # In-memory H2 database for integration tests
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop   # creates schema on startup, drops it on shutdown
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

app:
  jwt:
    secret: 9e+I4Bv5J/VrsCqW9oLVtD6gYfrAjey/mjOFMAWbUog=
    expiration-minutes: 60